dokuwiki_translator_homepage:
    path:  /
    defaults: { _controller: dokuwikiTranslatorBundle:Default:index }

dokuwiki_translator_show_extension:
    path:  /{type}/{name}
    defaults: { _controller: dokuwikiTranslatorBundle:Extension:show}
    requirements:
        type: plugin|template

dokuwiki_translator_extension_add:
    path:  /{type}
    defaults: { _controller: dokuwikiTranslatorBundle:Extension:index}
    requirements:
        type: plugin|template

dokuwiki_translator_extension_activate:
    path:  /{type}/{name}/activate/{key}
    defaults: { _controller: dokuwikiTranslatorBundle:Extension:activate}
    requirements:
        type: plugin|template

dokuwiki_translator_extension_settings:
    path:  /{type}/{name}/settings
    defaults: { _controller: dokuwikiTranslatorBundle:Extension:settings}
    requirements:
        type: plugin|template

dokuwiki_translator_extension_edit:
    path:  /{type}/{name}/edit/{key}
    defaults: { _controller: dokuwikiTranslatorBundle:Extension:edit}
    requirements:
        type: plugin|template

dokuwiki_translate:
    path:  /translate/dokuwiki
    defaults: { _controller: dokuwikiTranslatorBundle:Translation:translateCore }

dokuwiki_translate_extension:
    path:  /translate/{type}/{name}
    defaults: { _controller: dokuwikiTranslatorBundle:Translation:translateExtension}
    requirements:
        type: plugin|template

dokuwiki_translate_thanks:
    path:  /translate/thanks
    defaults: { _controller: dokuwikiTranslatorBundle:Translation:thanks }

dokuwiki_translate_save:
    path:  /translate/save
    defaults: { _controller: dokuwikiTranslatorBundle:Translation:save}

dokuwiki_translator_show:
    path:  /dokuwiki
    defaults: { _controller: dokuwikiTranslatorBundle:Default:show}

dokuwiki_translator_redirect_old:
    path: /translate.php
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /
        permanent: true
