parameters:
    repository.class: org\dokuwiki\translatorBundle\Services\Repository\Repository
    repository_manager.class: org\dokuwiki\translatorBundle\Services\Repository\RepositoryManager
    repository_stats.class: org\dokuwiki\translatorBundle\Services\Repository\RepositoryStats
    doku_wiki_repository_api.class: org\dokuwiki\translatorBundle\Services\DokuWikiRepositoryAPI\DokuWikiRepositoryAPI
    plugin_name_validator.class: org\dokuwiki\translatorBundle\Validator\PluginNameValidator
    language_manager.class: org\dokuwiki\translatorBundle\Services\Language\LanguageManager

services:
    repository_manager:
        class: '%repository_manager.class%'
        arguments: ['%data%', '@doctrine.orm.entity_manager', '%repositoryUpdateAge%', '%maxRepositoriesToUpdatePerRun%', '@repository_stats' , '@git_service', '@mail_service', '@git_hub_service', '@logger', '%maxErrorCount%', '@git_hub_status_service']

    repository_stats:
        class: '%repository_stats.class%'
        arguments: [ '@doctrine.orm.entity_manager']

    doku_wiki_repository_api:
        class: '%doku_wiki_repository_api.class%'
        arguments: ['%data%', '@doctrine.orm.entity_manager']

    plugin_name_validator:
        class: org\dokuwiki\translatorBundle\Validator\PluginNameValidator
        tags:
            - { name: validator.constraint_validator, alias: dwplugin }
        calls:
            - [setApi, ['@doku_wiki_repository_api']]

    template_name_validator:
        class: org\dokuwiki\translatorBundle\Validator\TemplateNameValidator
        tags:
            - { name: validator.constraint_validator, alias: dwtemplate }
        calls:
            - [setApi, ['@doku_wiki_repository_api']]

    custom_unique_entity_validator:
        class: org\dokuwiki\translatorBundle\Validator\CustomUniqueEntityValidator
        tags:
            - { name: validator.constraint_validator, alias: customuniqueentity }
        arguments: ['@doctrine']

    language_manager:
        class: "%language_manager.class%"

    listener.before_controller:
        class: org\dokuwiki\translatorBundle\EventListener\BeforeControllerListener
        tags:
            - { name: kernel.event_listener, event: 'kernel.controller', method: 'onKernelController' }

    listener.kernel_exception:
        class: org\dokuwiki\translatorBundle\EventListener\RouteNotFoundExceptionListener
        arguments: ['@logger', '@twig']
        tags:
            - { name: kernel.event_listener, event: 'kernel.exception', method: 'onKernelException' }

    git_service:
        class: org\dokuwiki\translatorBundle\Services\Git\GitService
        arguments: ['%git_bin%', '%command_timeout%']

    mail_service:
        class: org\dokuwiki\translatorBundle\Services\Mail\MailService
        arguments: ['@mailer', '@twig', '%mailer_from%', '@logger']

    git_hub_service:
        class: org\dokuwiki\translatorBundle\Services\GitHub\GitHubService
        arguments: ['%git_hub_token%', '%data%', '%git_hub_url%']

    git_hub_status_service:
        class: org\dokuwiki\translatorBundle\Services\GitHub\GitHubStatusService
        arguments: []

    user_translation_validator_factory:
        class: org\dokuwiki\translatorBundle\Services\Language\UserTranslationValidatorFactory
        arguments: ['@validator']

    translation_preparer:
        class: org\dokuwiki\translatorBundle\Services\Language\TranslationPreparer

    doku_wiki_toolbar_extension:
        class: org\dokuwiki\translatorBundle\Twig\DokuWikiToolbarExtension
        tags:
            - { name: twig.extension }

    highlight_whitespace:
            class: org\dokuwiki\translatorBundle\Twig\HighlightWhitespaceExtension
            tags:
                - { name: twig.extension }
